name: Deploy to Production
on:
    push:
        branches: ["main"]

jobs: 
    redeploy_project:
        runs-on: ubuntu-latest
        name: Deploying the Project with CI-CD
        steps:
            - run: |
                echo "${{secrets.SSH_PRIVATE_KEY_GCP}}" &> ~/ssh_key
                chmod 700 home/runner/ssh_key
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no tanishq@34.10.32.117 -t "sudo docker stop main-app && sudo docker rm main-app && sudo docker run --name main-app -p 5173:5173 -d graniteviper/apple:latest"
